### ISSUE TITLE
[Improvement] Adding more info in `README.md`

### ISSUE THREAD

**Issue by iatharva** [amishasinghh/Responsive-Netflix-LandingPage-Clone#1]
Adding the screenshot of how the page actually looks would be more informational.
Also, I saw that you have deployed it on Github pages, adding that link in `README.md` would be helpful for people to access it.

You can close this issue if it's not relevant or if it's solved.
Hope this is helpful.

**Comment by amishasinghh** [comment]
Have made the changes, thank you for your inputs!
